/**
 * @flow
 */

import * as React from 'react';
import * as ReactStylesheet from '../src/index';
import * as CSS from '../src/CSS';
import * as Compiler from '../src/Compiler';

// Just a little helper to define references to CSS variables.
function variable(name, scope = 'base') {
  name = Compiler.compileName(name);
  const fallback = scope === 'base' ? 'initial' : `var(--base-${name}, initial)`;
  return (`var(--${scope}-${name}, ${fallback})`: any);
}

// Define a base stylesheet which just defines a lot of placeholders, like
// really a lot
const base = ReactStylesheet.createStylesheet({
  displayName: 'base',
  base: {
    color: variable('color', 'base'),
    display: variable('display', 'base'),
    position: variable('position', 'base'),
    width: variable('width', 'base'),
    minWidth: variable('minWidth', 'base'),
    maxWidth: variable('maxWidth', 'base'),
    height: variable('height', 'base'),
    minHeight: variable('minHeight', 'base'),
    maxHeight: variable('maxHeight', 'base'),
    top: variable('top', 'base'),
    bottom: variable('bottom', 'base'),
    left: variable('left', 'base'),
    right: variable('right', 'base'),
    startOffset: variable('startOffset', 'base'),
    endOffset: variable('endOffset', 'base'),
    padding: variable('padding', 'base'),
    paddingLeft: variable('paddingLeft', 'base'),
    paddingRight: variable('paddingRight', 'base'),
    paddingTop: variable('paddingTop', 'base'),
    paddingBottom: variable('paddingBottom', 'base'),
    paddingStart: variable('paddingStart', 'base'),
    paddingEnd: variable('paddingEnd', 'base'),
    paddingVertical: variable('paddingVertical', 'base'),
    paddingHorizontal: variable('paddingHorizontal', 'base'),
    margin: variable('margin', 'base'),
    marginLeft: variable('marginLeft', 'base'),
    marginRight: variable('marginRight', 'base'),
    marginTop: variable('marginTop', 'base'),
    marginBottom: variable('marginBottom', 'base'),
    marginStart: variable('marginStart', 'base'),
    marginEnd: variable('marginEnd', 'base'),
    marginVertical: variable('marginVertical', 'base'),
    marginHorizontal: variable('marginHorizontal', 'base'),
    all: variable('all', 'base'),
    animation: variable('animation', 'base'),
    animationDelay: variable('animationDelay', 'base'),
    animationDirection: variable('animationDirection', 'base'),
    animationDuration: variable('animationDuration', 'base'),
    animationFillMode: variable('animationFillMode', 'base'),
    animationIterationCount: variable('animationIterationCount', 'base'),
    animationName: variable('animationName', 'base'),
    animationPlayState: variable('animationPlayState', 'base'),
    animationTimingFunction: variable('animationTimingFunction', 'base'),
    appearance: variable('appearance', 'base'),
    backdropFilter: variable('backdropFilter', 'base'),
    backfaceVisibility: variable('backfaceVisibility', 'base'),
    background: variable('background', 'base'),
    backgroundAttachment: variable('backgroundAttachment', 'base'),
    backgroundBlendMode: variable('backgroundBlendMode', 'base'),
    backgroundClip: variable('backgroundClip', 'base'),
    backgroundColor: variable('backgroundColor', 'base'),
    backgroundImage: variable('backgroundImage', 'base'),
    backgroundOrigin: variable('backgroundOrigin', 'base'),
    backgroundPosition: variable('backgroundPosition', 'base'),
    backgroundPositionX: variable('backgroundPositionX', 'base'),
    backgroundPositionY: variable('backgroundPositionY', 'base'),
    backgroundRepeat: variable('backgroundRepeat', 'base'),
    backgroundSize: variable('backgroundSize', 'base'),
    borderRadius: variable('borderRadius', 'base'),
    borderBottomLeftRadius: variable('borderBottomLeftRadius', 'base'),
    borderBottomRightRadius: variable('borderBottomRightRadius', 'base'),
    borderTopLeftRadius: variable('borderTopLeftRadius', 'base'),
    borderTopRightRadius: variable('borderTopRightRadius', 'base'),
    borderCollapse: variable('borderCollapse', 'base'),
    borderSpacing: variable('borderSpacing', 'base'),
    border: variable('border', 'base'),
    borderColor: variable('borderColor', 'base'),
    borderStyle: variable('borderStyle', 'base'),
    borderWidth: variable('borderWidth', 'base'),
    borderBottom: variable('borderBottom', 'base'),
    borderBottomColor: variable('borderBottomColor', 'base'),
    borderBottomStyle: variable('borderBottomStyle', 'base'),
    borderBottomWidth: variable('borderBottomWidth', 'base'),
    borderLeft: variable('borderLeft', 'base'),
    borderLeftColor: variable('borderLeftColor', 'base'),
    borderLeftStyle: variable('borderLeftStyle', 'base'),
    borderLeftWidth: variable('borderLeftWidth', 'base'),
    borderRight: variable('borderRight', 'base'),
    borderRightColor: variable('borderRightColor', 'base'),
    borderRightStyle: variable('borderRightStyle', 'base'),
    borderRightWidth: variable('borderRightWidth', 'base'),
    borderTop: variable('borderTop', 'base'),
    borderTopColor: variable('borderTopColor', 'base'),
    borderTopStyle: variable('borderTopStyle', 'base'),
    borderTopWidth: variable('borderTopWidth', 'base'),
    boxShadow: variable('boxShadow', 'base'),
    boxSizing: variable('boxSizing', 'base'),
    float: variable('float', 'base'),
    clear: variable('clear', 'base'),
    content: variable('content', 'base'),
    cursor: variable('cursor', 'base'),
    direction: variable('direction', 'base'),
    flex: variable('flex', 'base'),
    flexBasis: variable('flexBasis', 'base'),
    flexDirection: variable('flexDirection', 'base'),
    flexFlow: variable('flexFlow', 'base'),
    flexGrow: variable('flexGrow', 'base'),
    flexShrink: variable('flexShrink', 'base'),
    flexWrap: variable('flexWrap', 'base'),
    justifyContent: variable('justifyContent', 'base'),
    alignItems: variable('alignItems', 'base'),
    alignSelf: variable('alignSelf', 'base'),
    alignContent: variable('alignContent', 'base'),
    order: variable('order', 'base'),
    font: variable('font', 'base'),
    fontFamily: variable('fontFamily', 'base'),
    fontSize: variable('fontSize', 'base'),
    fontStyle: variable('fontStyle', 'base'),
    fontWeight: variable('fontWeight', 'base'),
    lineHeight: variable('lineHeight', 'base'),
    listStyle: variable('listStyle', 'base'),
    listStyleImage: variable('listStyleImage', 'base'),
    listStylePosition: variable('listStylePosition', 'base'),
    listStyleType: variable('listStyleType', 'base'),
    opacity: variable('opacity', 'base'),
    outline: variable('outline', 'base'),
    outlineColor: variable('outlineColor', 'base'),
    outlineOffset: variable('outlineOffset', 'base'),
    outlineStyle: variable('outlineStyle', 'base'),
    outlineWidth: variable('outlineWidth', 'base'),
    overflow: variable('overflow', 'base'),
    overflowX: variable('overflowX', 'base'),
    overflowY: variable('overflowY', 'base'),
    pointerEvents: variable('pointerEvents', 'base'),
    resize: variable('resize', 'base'),
    textAlign: variable('textAlign', 'base'),
    textDecoration: variable('textDecoration', 'base'),
    textOverflow: variable('textOverflow', 'base'),
    textShadow: variable('textShadow', 'base'),
    textTransform: variable('textTransform', 'base'),
    transform: variable('transform', 'base'),
    transformBox: variable('transformBox', 'base'),
    transformOrigin: variable('transformOrigin', 'base'),
    transformStyle: variable('transformStyle', 'base'),
    transition: variable('transition', 'base'),
    transitionDelay: variable('transitionDelay', 'base'),
    transitionDuration: variable('transitionDuration', 'base'),
    transitionProperty: variable('transitionProperty', 'base'),
    transitionTimingFunction: variable('transitionTimingFunction', 'base'),
    userSelect: variable('userSelect', 'base'),
    verticalAlign: variable('verticalAlign', 'base'),
    visibility: variable('visibility', 'base'),
    whiteSpace: variable('whiteSpace', 'base'),
    zIndex: variable('zIndex', 'base'),
    hover: {
      display: variable('display', 'hover'),
      position: variable('position', 'hover'),
      width: variable('width', 'hover'),
      minWidth: variable('minWidth', 'hover'),
      maxWidth: variable('maxWidth', 'hover'),
      height: variable('height', 'hover'),
      minHeight: variable('minHeight', 'hover'),
      maxHeight: variable('maxHeight', 'hover'),
      top: variable('top', 'hover'),
      bottom: variable('bottom', 'hover'),
      left: variable('left', 'hover'),
      right: variable('right', 'hover'),
      startOffset: variable('startOffset', 'hover'),
      endOffset: variable('endOffset', 'hover'),
      padding: variable('padding', 'hover'),
      paddingLeft: variable('paddingLeft', 'hover'),
      paddingRight: variable('paddingRight', 'hover'),
      paddingTop: variable('paddingTop', 'hover'),
      paddingBottom: variable('paddingBottom', 'hover'),
      paddingStart: variable('paddingStart', 'hover'),
      paddingEnd: variable('paddingEnd', 'hover'),
      paddingVertical: variable('paddingVertical', 'hover'),
      paddingHorizontal: variable('paddingHorizontal', 'hover'),
      margin: variable('margin', 'hover'),
      marginLeft: variable('marginLeft', 'hover'),
      marginRight: variable('marginRight', 'hover'),
      marginTop: variable('marginTop', 'hover'),
      marginBottom: variable('marginBottom', 'hover'),
      marginStart: variable('marginStart', 'hover'),
      marginEnd: variable('marginEnd', 'hover'),
      marginVertical: variable('marginVertical', 'hover'),
      marginHorizontal: variable('marginHorizontal', 'hover'),
      all: variable('all', 'hover'),
      animation: variable('animation', 'hover'),
      animationDelay: variable('animationDelay', 'hover'),
      animationDirection: variable('animationDirection', 'hover'),
      animationDuration: variable('animationDuration', 'hover'),
      animationFillMode: variable('animationFillMode', 'hover'),
      animationIterationCount: variable('animationIterationCount', 'hover'),
      animationName: variable('animationName', 'hover'),
      animationPlayState: variable('animationPlayState', 'hover'),
      animationTimingFunction: variable('animationTimingFunction', 'hover'),
      appearance: variable('appearance', 'hover'),
      backdropFilter: variable('backdropFilter', 'hover'),
      backfaceVisibility: variable('backfaceVisibility', 'hover'),
      background: variable('background', 'hover'),
      backgroundAttachment: variable('backgroundAttachment', 'hover'),
      backgroundBlendMode: variable('backgroundBlendMode', 'hover'),
      backgroundClip: variable('backgroundClip', 'hover'),
      backgroundColor: variable('backgroundColor', 'hover'),
      backgroundImage: variable('backgroundImage', 'hover'),
      backgroundOrigin: variable('backgroundOrigin', 'hover'),
      backgroundPosition: variable('backgroundPosition', 'hover'),
      backgroundPositionX: variable('backgroundPositionX', 'hover'),
      backgroundPositionY: variable('backgroundPositionY', 'hover'),
      backgroundRepeat: variable('backgroundRepeat', 'hover'),
      backgroundSize: variable('backgroundSize', 'hover'),
      borderRadius: variable('borderRadius', 'hover'),
      borderBottomLeftRadius: variable('borderBottomLeftRadius', 'hover'),
      borderBottomRightRadius: variable('borderBottomRightRadius', 'hover'),
      borderTopLeftRadius: variable('borderTopLeftRadius', 'hover'),
      borderTopRightRadius: variable('borderTopRightRadius', 'hover'),
      borderCollapse: variable('borderCollapse', 'hover'),
      borderSpacing: variable('borderSpacing', 'hover'),
      border: variable('border', 'hover'),
      borderColor: variable('borderColor', 'hover'),
      borderStyle: variable('borderStyle', 'hover'),
      borderWidth: variable('borderWidth', 'hover'),
      borderBottom: variable('borderBottom', 'hover'),
      borderBottomColor: variable('borderBottomColor', 'hover'),
      borderBottomStyle: variable('borderBottomStyle', 'hover'),
      borderBottomWidth: variable('borderBottomWidth', 'hover'),
      borderLeft: variable('borderLeft', 'hover'),
      borderLeftColor: variable('borderLeftColor', 'hover'),
      borderLeftStyle: variable('borderLeftStyle', 'hover'),
      borderLeftWidth: variable('borderLeftWidth', 'hover'),
      borderRight: variable('borderRight', 'hover'),
      borderRightColor: variable('borderRightColor', 'hover'),
      borderRightStyle: variable('borderRightStyle', 'hover'),
      borderRightWidth: variable('borderRightWidth', 'hover'),
      borderTop: variable('borderTop', 'hover'),
      borderTopColor: variable('borderTopColor', 'hover'),
      borderTopStyle: variable('borderTopStyle', 'hover'),
      borderTopWidth: variable('borderTopWidth', 'hover'),
      boxShadow: variable('boxShadow', 'hover'),
      boxSizing: variable('boxSizing', 'hover'),
      float: variable('float', 'hover'),
      clear: variable('clear', 'hover'),
      content: variable('content', 'hover'),
      cursor: variable('cursor', 'hover'),
      direction: variable('direction', 'hover'),
      flex: variable('flex', 'hover'),
      flexBasis: variable('flexBasis', 'hover'),
      flexDirection: variable('flexDirection', 'hover'),
      flexFlow: variable('flexFlow', 'hover'),
      flexGrow: variable('flexGrow', 'hover'),
      flexShrink: variable('flexShrink', 'hover'),
      flexWrap: variable('flexWrap', 'hover'),
      justifyContent: variable('justifyContent', 'hover'),
      alignItems: variable('alignItems', 'hover'),
      alignSelf: variable('alignSelf', 'hover'),
      alignContent: variable('alignContent', 'hover'),
      order: variable('order', 'hover'),
      font: variable('font', 'hover'),
      fontFamily: variable('fontFamily', 'hover'),
      fontSize: variable('fontSize', 'hover'),
      fontStyle: variable('fontStyle', 'hover'),
      fontWeight: variable('fontWeight', 'hover'),
      lineHeight: variable('lineHeight', 'hover'),
      listStyle: variable('listStyle', 'hover'),
      listStyleImage: variable('listStyleImage', 'hover'),
      listStylePosition: variable('listStylePosition', 'hover'),
      listStyleType: variable('listStyleType', 'hover'),
      opacity: variable('opacity', 'hover'),
      outline: variable('outline', 'hover'),
      outlineColor: variable('outlineColor', 'hover'),
      outlineOffset: variable('outlineOffset', 'hover'),
      outlineStyle: variable('outlineStyle', 'hover'),
      outlineWidth: variable('outlineWidth', 'hover'),
      overflow: variable('overflow', 'hover'),
      overflowX: variable('overflowX', 'hover'),
      overflowY: variable('overflowY', 'hover'),
      pointerEvents: variable('pointerEvents', 'hover'),
      resize: variable('resize', 'hover'),
      textAlign: variable('textAlign', 'hover'),
      textDecoration: variable('textDecoration', 'hover'),
      textOverflow: variable('textOverflow', 'hover'),
      textShadow: variable('textShadow', 'hover'),
      textTransform: variable('textTransform', 'hover'),
      transform: variable('transform', 'hover'),
      transformBox: variable('transformBox', 'hover'),
      transformOrigin: variable('transformOrigin', 'hover'),
      transformStyle: variable('transformStyle', 'hover'),
      transition: variable('transition', 'hover'),
      transitionDelay: variable('transitionDelay', 'hover'),
      transitionDuration: variable('transitionDuration', 'hover'),
      transitionProperty: variable('transitionProperty', 'hover'),
      transitionTimingFunction: variable('transitionTimingFunction', 'hover'),
      userSelect: variable('userSelect', 'hover'),
      verticalAlign: variable('verticalAlign', 'hover'),
      visibility: variable('visibility', 'hover'),
      whiteSpace: variable('whiteSpace', 'hover'),
      zIndex: variable('zIndex', 'hover'),
    },
  },
});

// make sure stylesheet is in DOM
ReactStylesheet.injectStylesheet(base);

// Now we are going to define a component which set CSS variable values based on
// its props. Note that we can eitehr pass a base stylesheet or some override.

type ElementProps = CSS.CSSPropertySet & {
  stylesheet?: ReactStylesheet.Stylesheet,
  colorOnHover?: CSS.CSSColor,
  backgroundColorOnHover?: CSS.CSSColor,
};

function Element({
  stylesheet = base,
  // Base
  display,
  position,
  width,
  minWidth,
  maxWidth,
  height,
  minHeight,
  maxHeight,
  top,
  bottom,
  left,
  right,
  startOffset,
  endOffset,
  padding,
  paddingLeft,
  paddingRight,
  paddingTop,
  paddingBottom,
  paddingStart,
  paddingEnd,
  paddingVertical,
  paddingHorizontal,
  margin,
  marginLeft,
  marginRight,
  marginTop,
  marginBottom,
  marginStart,
  marginEnd,
  marginVertical,
  marginHorizontal,
  all,
  animation,
  animationDelay,
  animationDirection,
  animationDuration,
  animationFillMode,
  animationIterationCount,
  animationName,
  animationPlayState,
  animationTimingFunction,
  appearance,
  backdropFilter,
  backfaceVisibility,
  background,
  backgroundAttachment,
  backgroundBlendMode,
  backgroundClip,
  backgroundColor,
  backgroundImage,
  backgroundOrigin,
  backgroundPosition,
  backgroundPositionX,
  backgroundPositionY,
  backgroundRepeat,
  backgroundSize,
  borderRadius,
  borderBottomLeftRadius,
  borderBottomRightRadius,
  borderTopLeftRadius,
  borderTopRightRadius,
  borderCollapse,
  borderSpacing,
  border,
  borderColor,
  borderStyle,
  borderWidth,
  borderBottom,
  borderBottomColor,
  borderBottomStyle,
  borderBottomWidth,
  borderLeft,
  borderLeftColor,
  borderLeftStyle,
  borderLeftWidth,
  borderRight,
  borderRightColor,
  borderRightStyle,
  borderRightWidth,
  borderTop,
  borderTopColor,
  borderTopStyle,
  borderTopWidth,
  boxShadow,
  boxSizing,
  float,
  clear,
  content,
  cursor,
  direction,
  flex,
  flexBasis,
  flexDirection,
  flexFlow,
  flexGrow,
  flexShrink,
  flexWrap,
  justifyContent,
  alignItems,
  alignSelf,
  alignContent,
  order,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  lineHeight,
  listStyle,
  listStyleImage,
  listStylePosition,
  listStyleType,
  opacity,
  outline,
  outlineColor,
  outlineOffset,
  outlineStyle,
  outlineWidth,
  overflow,
  overflowX,
  overflowY,
  pointerEvents,
  resize,
  textAlign,
  textDecoration,
  textOverflow,
  textShadow,
  textTransform,
  transform,
  transformBox,
  transformOrigin,
  transformStyle,
  transition,
  transitionDelay,
  transitionDuration,
  transitionProperty,
  transitionTimingFunction,
  userSelect,
  verticalAlign,
  visibility,
  whiteSpace,
  zIndex,
  // Hover
  displayOnHover,
  positionOnHover,
  widthOnHover,
  minWidthOnHover,
  maxWidthOnHover,
  heightOnHover,
  minHeightOnHover,
  maxHeightOnHover,
  topOnHover,
  bottomOnHover,
  leftOnHover,
  rightOnHover,
  startOffsetOnHover,
  endOffsetOnHover,
  paddingOnHover,
  paddingLeftOnHover,
  paddingRightOnHover,
  paddingTopOnHover,
  paddingBottomOnHover,
  paddingStartOnHover,
  paddingEndOnHover,
  paddingVerticalOnHover,
  paddingHorizontalOnHover,
  marginOnHover,
  marginLeftOnHover,
  marginRightOnHover,
  marginTopOnHover,
  marginBottomOnHover,
  marginStartOnHover,
  marginEndOnHover,
  marginVerticalOnHover,
  marginHorizontalOnHover,
  allOnHover,
  animationOnHover,
  animationDelayOnHover,
  animationDirectionOnHover,
  animationDurationOnHover,
  animationFillModeOnHover,
  animationIterationCountOnHover,
  animationNameOnHover,
  animationPlayStateOnHover,
  animationTimingFunctionOnHover,
  appearanceOnHover,
  backdropFilterOnHover,
  backfaceVisibilityOnHover,
  backgroundOnHover,
  backgroundAttachmentOnHover,
  backgroundBlendModeOnHover,
  backgroundClipOnHover,
  backgroundColorOnHover,
  backgroundImageOnHover,
  backgroundOriginOnHover,
  backgroundPositionOnHover,
  backgroundPositionXOnHover,
  backgroundPositionYOnHover,
  backgroundRepeatOnHover,
  backgroundSizeOnHover,
  borderRadiusOnHover,
  borderBottomLeftRadiusOnHover,
  borderBottomRightRadiusOnHover,
  borderTopLeftRadiusOnHover,
  borderTopRightRadiusOnHover,
  borderCollapseOnHover,
  borderSpacingOnHover,
  borderOnHover,
  borderColorOnHover,
  borderStyleOnHover,
  borderWidthOnHover,
  borderBottomOnHover,
  borderBottomColorOnHover,
  borderBottomStyleOnHover,
  borderBottomWidthOnHover,
  borderLeftOnHover,
  borderLeftColorOnHover,
  borderLeftStyleOnHover,
  borderLeftWidthOnHover,
  borderRightOnHover,
  borderRightColorOnHover,
  borderRightStyleOnHover,
  borderRightWidthOnHover,
  borderTopOnHover,
  borderTopColorOnHover,
  borderTopStyleOnHover,
  borderTopWidthOnHover,
  boxShadowOnHover,
  boxSizingOnHover,
  floatOnHover,
  clearOnHover,
  contentOnHover,
  cursorOnHover,
  directionOnHover,
  flexOnHover,
  flexBasisOnHover,
  flexDirectionOnHover,
  flexFlowOnHover,
  flexGrowOnHover,
  flexShrinkOnHover,
  flexWrapOnHover,
  justifyContentOnHover,
  alignItemsOnHover,
  alignSelfOnHover,
  alignContentOnHover,
  orderOnHover,
  fontOnHover,
  fontFamilyOnHover,
  fontSizeOnHover,
  fontStyleOnHover,
  fontWeightOnHover,
  lineHeightOnHover,
  listStyleOnHover,
  listStyleImageOnHover,
  listStylePositionOnHover,
  listStyleTypeOnHover,
  opacityOnHover,
  outlineOnHover,
  outlineColorOnHover,
  outlineOffsetOnHover,
  outlineStyleOnHover,
  outlineWidthOnHover,
  overflowOnHover,
  overflowXOnHover,
  overflowYOnHover,
  pointerEventsOnHover,
  resizeOnHover,
  textAlignOnHover,
  textDecorationOnHover,
  textOverflowOnHover,
  textShadowOnHover,
  textTransformOnHover,
  transformOnHover,
  transformBoxOnHover,
  transformOriginOnHover,
  transformStyleOnHover,
  transitionOnHover,
  transitionDelayOnHover,
  transitionDurationOnHover,
  transitionPropertyOnHover,
  transitionTimingFunctionOnHover,
  userSelectOnHover,
  verticalAlignOnHover,
  visibilityOnHover,
  whiteSpaceOnHover,
  zIndexOnHover,
  // End
  ...props
}: ElementProps) {
  const style = {
    '--base-display': display,
    '--base-position': position,
    '--base-width': width,
    '--base-minWidth': minWidth,
    '--base-maxWidth': maxWidth,
    '--base-height': height,
    '--base-min-height': minHeight,
    '--base-max-height': maxHeight,
    '--base-top': top,
    '--base-bottom': bottom,
    '--base-left': left,
    '--base-right': right,
    '--base-start-offset': startOffset,
    '--base-end-offset': endOffset,
    '--base-padding': padding,
    '--base-padding-left': paddingLeft,
    '--base-padding-right': paddingRight,
    '--base-padding-top': paddingTop,
    '--base-padding-bottom': paddingBottom,
    '--base-padding-start': paddingStart,
    '--base-padding-end': paddingEnd,
    '--base-padding-vertical': paddingVertical,
    '--base-padding-horizontal': paddingHorizontal,
    '--base-margin': margin,
    '--base-margin-left': marginLeft,
    '--base-margin-right': marginRight,
    '--base-margin-top': marginTop,
    '--base-margin-bottom': marginBottom,
    '--base-margin-start': marginStart,
    '--base-margin-end': marginEnd,
    '--base-margin-vertical': marginVertical,
    '--base-margin-horizontal': marginHorizontal,
    '--base-all': all,
    '--base-animation': animation,
    '--base-animation-delay': animationDelay,
    '--base-animation-direction': animationDirection,
    '--base-animation-duration': animationDuration,
    '--base-animation-fill-mode': animationFillMode,
    '--base-animation-iteration-count': animationIterationCount,
    '--base-animation-name': animationName,
    '--base-animation-playState': animationPlayState,
    '--base-animation-timing-function': animationTimingFunction,
    '--base-appearance': appearance,
    '--base-backdrop-filter': backdropFilter,
    '--base-backface-visibility': backfaceVisibility,
    '--base-background': background,
    '--base-background-attachment': backgroundAttachment,
    '--base-background-blend-mode': backgroundBlendMode,
    '--base-background-clip': backgroundClip,
    '--base-background-color': backgroundColor,
    '--base-background-image': backgroundImage,
    '--base-background-origin': backgroundOrigin,
    '--base-background-position': backgroundPosition,
    '--base-background-positionX': backgroundPositionX,
    '--base-background-positionY': backgroundPositionY,
    '--base-background-repeat': backgroundRepeat,
    '--base-background-size': backgroundSize,
    '--base-border-radius': borderRadius,
    '--base-border-bottom-left-radius': borderBottomLeftRadius,
    '--base-border-bottom-right-radius': borderBottomRightRadius,
    '--base-border-top-left-radius': borderTopLeftRadius,
    '--base-border-top-right-radius': borderTopRightRadius,
    '--base-border-collapse': borderCollapse,
    '--base-border-spacing': borderSpacing,
    '--base-border': border,
    '--base-border-color': borderColor,
    '--base-border-style': borderStyle,
    '--base-border-width': borderWidth,
    '--base-border-bottom': borderBottom,
    '--base-border-bottom-color': borderBottomColor,
    '--base-border-bottom-style': borderBottomStyle,
    '--base-border-bottom-width': borderBottomWidth,
    '--base-border-left': borderLeft,
    '--base-border-left-color': borderLeftColor,
    '--base-border-left-style': borderLeftStyle,
    '--base-border-left-width': borderLeftWidth,
    '--base-border-right': borderRight,
    '--base-border-right-color': borderRightColor,
    '--base-border-right-style': borderRightStyle,
    '--base-border-right-width': borderRightWidth,
    '--base-border-top': borderTop,
    '--base-border-top-color': borderTopColor,
    '--base-border-top-style': borderTopStyle,
    '--base-border-top-width': borderTopWidth,
    '--base-box-shadow': boxShadow,
    '--base-box-sizing': boxSizing,
    '--base-float': float,
    '--base-clear': clear,
    '--base-content': content,
    '--base-cursor': cursor,
    '--base-direction': direction,
    '--base-flex': flex,
    '--base-flex-basis': flexBasis,
    '--base-flex-direction': flexDirection,
    '--base-flex-flow': flexFlow,
    '--base-flex-grow': flexGrow,
    '--base-flex-shrink': flexShrink,
    '--base-flex-wrap': flexWrap,
    '--base-justify-content': justifyContent,
    '--base-align-items': alignItems,
    '--base-align-self': alignSelf,
    '--base-align-content': alignContent,
    '--base-order': order,
    '--base-font': font,
    '--base-font-family': fontFamily,
    '--base-font-size': fontSize,
    '--base-font-style': fontStyle,
    '--base-font-weight': fontWeight,
    '--base-line-height': lineHeight,
    '--base-list-style': listStyle,
    '--base-list-style-image': listStyleImage,
    '--base-list-style-position': listStylePosition,
    '--base-list-style-type': listStyleType,
    '--base-opacity': opacity,
    '--base-outline': outline,
    '--base-outline-color': outlineColor,
    '--base-outline-offset': outlineOffset,
    '--base-outline-style': outlineStyle,
    '--base-outline-width': outlineWidth,
    '--base-overflow': overflow,
    '--base-overflow-x': overflowX,
    '--base-overflow-y': overflowY,
    '--base-pointer-events': pointerEvents,
    '--base-resize': resize,
    '--base-text-align': textAlign,
    '--base-text-decoration': textDecoration,
    '--base-text-overflow': textOverflow,
    '--base-text-shadow': textShadow,
    '--base-text-transform': textTransform,
    '--base-transform': transform,
    '--base-transform-box': transformBox,
    '--base-transform-origin': transformOrigin,
    '--base-transform-style': transformStyle,
    '--base-transition': transition,
    '--base-transition-delay': transitionDelay,
    '--base-transition-duration': transitionDuration,
    '--base-transition-property': transitionProperty,
    '--base-transition-timing-function': transitionTimingFunction,
    '--base-user-select': userSelect,
    '--base-vertical-align': verticalAlign,
    '--base-visibility': visibility,
    '--base-whiteSpace': whiteSpace,
    '--base-z-ndex': zIndex,
    // Hover
    '--hover-display': displayOnHover,
    '--hover-position': positionOnHover,
    '--hover-width': widthOnHover,
    '--hover-minWidth': minWidthOnHover,
    '--hover-maxWidth': maxWidthOnHover,
    '--hover-height': heightOnHover,
    '--hover-min-height': minHeightOnHover,
    '--hover-max-height': maxHeightOnHover,
    '--hover-top': topOnHover,
    '--hover-bottom': bottomOnHover,
    '--hover-left': leftOnHover,
    '--hover-right': rightOnHover,
    '--hover-start-offset': startOffsetOnHover,
    '--hover-end-offset': endOffsetOnHover,
    '--hover-padding': paddingOnHover,
    '--hover-padding-left': paddingLeftOnHover,
    '--hover-padding-right': paddingRightOnHover,
    '--hover-padding-top': paddingTopOnHover,
    '--hover-padding-bottom': paddingBottomOnHover,
    '--hover-padding-start': paddingStartOnHover,
    '--hover-padding-end': paddingEndOnHover,
    '--hover-padding-vertical': paddingVerticalOnHover,
    '--hover-padding-horizontal': paddingHorizontalOnHover,
    '--hover-margin': marginOnHover,
    '--hover-margin-left': marginLeftOnHover,
    '--hover-margin-right': marginRightOnHover,
    '--hover-margin-top': marginTopOnHover,
    '--hover-margin-bottom': marginBottomOnHover,
    '--hover-margin-start': marginStartOnHover,
    '--hover-margin-end': marginEndOnHover,
    '--hover-margin-vertical': marginVerticalOnHover,
    '--hover-margin-horizontal': marginHorizontalOnHover,
    '--hover-all': allOnHover,
    '--hover-animation': animationOnHover,
    '--hover-animation-delay': animationDelayOnHover,
    '--hover-animation-direction': animationDirectionOnHover,
    '--hover-animation-duration': animationDurationOnHover,
    '--hover-animation-fill-mode': animationFillModeOnHover,
    '--hover-animation-iteration-count': animationIterationCountOnHover,
    '--hover-animation-name': animationNameOnHover,
    '--hover-animation-playState': animationPlayStateOnHover,
    '--hover-animation-timing-function': animationTimingFunctionOnHover,
    '--hover-appearance': appearanceOnHover,
    '--hover-backdrop-filter': backdropFilterOnHover,
    '--hover-backface-visibility': backfaceVisibilityOnHover,
    '--hover-background': backgroundOnHover,
    '--hover-background-attachment': backgroundAttachmentOnHover,
    '--hover-background-blend-mode': backgroundBlendModeOnHover,
    '--hover-background-clip': backgroundClipOnHover,
    '--hover-background-color': backgroundColorOnHover,
    '--hover-background-image': backgroundImageOnHover,
    '--hover-background-origin': backgroundOriginOnHover,
    '--hover-background-position': backgroundPositionOnHover,
    '--hover-background-positionX': backgroundPositionXOnHover,
    '--hover-background-positionY': backgroundPositionYOnHover,
    '--hover-background-repeat': backgroundRepeatOnHover,
    '--hover-background-size': backgroundSizeOnHover,
    '--hover-border-radius': borderRadiusOnHover,
    '--hover-border-bottom-left-radius': borderBottomLeftRadiusOnHover,
    '--hover-border-bottom-right-radius': borderBottomRightRadiusOnHover,
    '--hover-border-top-left-radius': borderTopLeftRadiusOnHover,
    '--hover-border-top-right-radius': borderTopRightRadiusOnHover,
    '--hover-border-collapse': borderCollapseOnHover,
    '--hover-border-spacing': borderSpacingOnHover,
    '--hover-border': borderOnHover,
    '--hover-border-color': borderColorOnHover,
    '--hover-border-style': borderStyleOnHover,
    '--hover-border-width': borderWidthOnHover,
    '--hover-border-bottom': borderBottomOnHover,
    '--hover-border-bottom-color': borderBottomColorOnHover,
    '--hover-border-bottom-style': borderBottomStyleOnHover,
    '--hover-border-bottom-width': borderBottomWidthOnHover,
    '--hover-border-left': borderLeftOnHover,
    '--hover-border-left-color': borderLeftColorOnHover,
    '--hover-border-left-style': borderLeftStyleOnHover,
    '--hover-border-left-width': borderLeftWidthOnHover,
    '--hover-border-right': borderRightOnHover,
    '--hover-border-right-color': borderRightColorOnHover,
    '--hover-border-right-style': borderRightStyleOnHover,
    '--hover-border-right-width': borderRightWidthOnHover,
    '--hover-border-top': borderTopOnHover,
    '--hover-border-top-color': borderTopColorOnHover,
    '--hover-border-top-style': borderTopStyleOnHover,
    '--hover-border-top-width': borderTopWidthOnHover,
    '--hover-box-shadow': boxShadowOnHover,
    '--hover-box-sizing': boxSizingOnHover,
    '--hover-float': floatOnHover,
    '--hover-clear': clearOnHover,
    '--hover-content': contentOnHover,
    '--hover-cursor': cursorOnHover,
    '--hover-direction': directionOnHover,
    '--hover-flex': flexOnHover,
    '--hover-flex-basis': flexBasisOnHover,
    '--hover-flex-direction': flexDirectionOnHover,
    '--hover-flex-flow': flexFlowOnHover,
    '--hover-flex-grow': flexGrowOnHover,
    '--hover-flex-shrink': flexShrinkOnHover,
    '--hover-flex-wrap': flexWrapOnHover,
    '--hover-justify-content': justifyContentOnHover,
    '--hover-align-items': alignItemsOnHover,
    '--hover-align-self': alignSelfOnHover,
    '--hover-align-content': alignContentOnHover,
    '--hover-order': orderOnHover,
    '--hover-font': fontOnHover,
    '--hover-font-family': fontFamilyOnHover,
    '--hover-font-size': fontSizeOnHover,
    '--hover-font-style': fontStyleOnHover,
    '--hover-font-weight': fontWeightOnHover,
    '--hover-line-height': lineHeightOnHover,
    '--hover-list-style': listStyleOnHover,
    '--hover-list-style-image': listStyleImageOnHover,
    '--hover-list-style-position': listStylePositionOnHover,
    '--hover-list-style-type': listStyleTypeOnHover,
    '--hover-opacity': opacityOnHover,
    '--hover-outline': outlineOnHover,
    '--hover-outline-color': outlineColorOnHover,
    '--hover-outline-offset': outlineOffsetOnHover,
    '--hover-outline-style': outlineStyleOnHover,
    '--hover-outline-width': outlineWidthOnHover,
    '--hover-overflow': overflowOnHover,
    '--hover-overflow-x': overflowXOnHover,
    '--hover-overflow-y': overflowYOnHover,
    '--hover-pointer-events': pointerEventsOnHover,
    '--hover-resize': resizeOnHover,
    '--hover-text-align': textAlignOnHover,
    '--hover-text-decoration': textDecorationOnHover,
    '--hover-text-overflow': textOverflowOnHover,
    '--hover-text-shadow': textShadowOnHover,
    '--hover-text-transform': textTransformOnHover,
    '--hover-transform': transformOnHover,
    '--hover-transform-box': transformBoxOnHover,
    '--hover-transform-origin': transformOriginOnHover,
    '--hover-transform-style': transformStyleOnHover,
    '--hover-transition': transitionOnHover,
    '--hover-transition-delay': transitionDelayOnHover,
    '--hover-transition-duration': transitionDurationOnHover,
    '--hover-transition-property': transitionPropertyOnHover,
    '--hover-transition-timing-function': transitionTimingFunctionOnHover,
    '--hover-user-select': userSelectOnHover,
    '--hover-vertical-align': verticalAlignOnHover,
    '--hover-visibility': visibilityOnHover,
    '--hover-whiteSpace': whiteSpaceOnHover,
    '--hover-z-index': zIndexOnHover,
  };
  const className = ReactStylesheet.toClassName(stylesheet, {});
  return <div {...props} className={className} style={style} />;
}

// Now usage is pretty simple.

export default function ProtoStyle() {
  return (
    <div>
      <Element
        color="red"
        colorOnHover="green"
        backgroundColor="green"
        backgroundColorOnHover="red">
        OK
      </Element>
    </div>
  );
}
