// @flow
export type msOverflowStyle = "auto" | "none" | "scrollbar" | "-ms-autohiding-scrollbar";
export type mozAppearance = "none" | "button" | "button-arrow-down" | "button-arrow-next" | "button-arrow-previous" | "button-arrow-up" | "button-bevel" | "button-focus" | "caret" | "checkbox" | "checkbox-container" | "checkbox-label" | "checkmenuitem" | "dualbutton" | "groupbox" | "listbox" | "listitem" | "menuarrow" | "menubar" | "menucheckbox" | "menuimage" | "menuitem" | "menuitemtext" | "menulist" | "menulist-button" | "menulist-text" | "menulist-textfield" | "menupopup" | "menuradio" | "menuseparator" | "meterbar" | "meterchunk" | "progressbar" | "progressbar-vertical" | "progresschunk" | "progresschunk-vertical" | "radio" | "radio-container" | "radio-label" | "radiomenuitem" | "range" | "range-thumb" | "resizer" | "resizerpanel" | "scale-horizontal" | "scalethumbend" | "scalethumb-horizontal" | "scalethumbstart" | "scalethumbtick" | "scalethumb-vertical" | "scale-vertical" | "scrollbarbutton-down" | "scrollbarbutton-left" | "scrollbarbutton-right" | "scrollbarbutton-up" | "scrollbarthumb-horizontal" | "scrollbarthumb-vertical" | "scrollbartrack-horizontal" | "scrollbartrack-vertical" | "searchfield" | "separator" | "sheet" | "spinner" | "spinner-downbutton" | "spinner-textfield" | "spinner-upbutton" | "splitter" | "statusbar" | "statusbarpanel" | "tab" | "tabpanel" | "tabpanels" | "tab-scroll-arrow-back" | "tab-scroll-arrow-forward" | "textfield" | "textfield-multiline" | "toolbar" | "toolbarbutton" | "toolbarbutton-dropdown" | "toolbargripper" | "toolbox" | "tooltip" | "treeheader" | "treeheadercell" | "treeheadersortarrow" | "treeitem" | "treeline" | "treetwisty" | "treetwistyopen" | "treeview" | "-moz-mac-unified-toolbar" | "-moz-win-borderless-glass" | "-moz-win-browsertabbar-toolbox" | "-moz-win-communicationstext" | "-moz-win-communications-toolbox" | "-moz-win-exclude-glass" | "-moz-win-glass" | "-moz-win-mediatext" | "-moz-win-media-toolbox" | "-moz-window-button-box" | "-moz-window-button-box-maximized" | "-moz-window-button-close" | "-moz-window-button-maximize" | "-moz-window-button-minimize" | "-moz-window-button-restore" | "-moz-window-frame-bottom" | "-moz-window-frame-left" | "-moz-window-frame-right" | "-moz-window-titlebar" | "-moz-window-titlebar-maximized";
export type mozBinding = string | "none";
export type mozBorderBottomColors = string | colorT | "none";
export type mozBorderLeftColors = string | colorT | "none";
export type mozBorderRightColors = string | colorT | "none";
export type mozBorderTopColors = string | colorT | "none";
export type mozFloatEdge = "border-box" | "content-box" | "margin-box" | "padding-box";
export type mozForceBrokenImageIcon = number;
export type mozImageRegion = string;
export type mozOrient = "inline" | "block" | "horizontal" | "vertical";
export type mozOutlineRadius = outlineRadiusT | string;
export type mozOutlineRadiusBottomleft = outlineRadiusT;
export type mozOutlineRadiusBottomright = outlineRadiusT;
export type mozOutlineRadiusTopleft = outlineRadiusT;
export type mozOutlineRadiusTopright = outlineRadiusT;
export type mozStackSizing = "ignore" | "stretch-to-fit";
export type mozTextBlink = "none" | "blink";
export type mozUserFocus = "ignore" | "normal" | "select-after" | "select-before" | "select-menu" | "select-same" | "select-all" | "none";
export type mozUserInput = "none" | "enabled" | "disabled";
export type mozUserModify = "read-only" | "read-write" | "write-only";
export type mozWindowShadow = "default" | "menu" | "tooltip" | "sheet" | "none";
export type webkitBorderBefore = borderWidth | borderStyle | color;
export type webkitBorderBeforeColor = color;
export type webkitBorderBeforeStyle = borderStyle;
export type webkitBorderBeforeWidth = borderWidth;
export type webkitBoxReflect = string | number;
export type webkitMask = maskImageT | string;
export type webkitMaskAttachment = attachmentT | string;
export type webkitMaskClip = webkitMaskClipStyleT | string;
export type webkitMaskComposite = compositeStyleT | string;
export type webkitMaskImage = maskImageT | string;
export type webkitMaskOrigin = string;
export type webkitMaskPosition = string;
export type webkitMaskPositionX = string;
export type webkitMaskPositionY = string;
export type webkitMaskRepeat = repeatStyleT | string;
export type webkitMaskRepeatX = "repeat" | "no-repeat" | "space" | "round";
export type webkitMaskRepeatY = "repeat" | "no-repeat" | "space" | "round";
export type webkitTapHighlightColor = colorT;
export type webkitTextFillColor = colorT;
export type webkitTextStroke = number | colorT;
export type webkitTextStrokeColor = colorT;
export type webkitTextStrokeWidth = number;
export type webkitTouchCallout = "default" | "none";
export type alignContent = "flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "stretch";
export type alignItems = "flex-start" | "flex-end" | "center" | "baseline" | "stretch";
export type alignSelf = "auto" | "flex-start" | "flex-end" | "center" | "baseline" | "stretch";
export type all = "initial" | "inherit" | "unset";
export type animation = singleAnimationT;
export type animationDelay = number;
export type animationDirection = singleAnimationDirectionT;
export type animationDuration = number;
export type animationFillMode = singleAnimationFillModeT;
export type animationIterationCount = singleAnimationIterationCountT;
export type animationName = singleAnimationNameT;
export type animationPlayState = singleAnimationPlayStateT;
export type animationTimingFunction = singleTimingFunctionT;
export type appearance = "auto" | "none";
export type azimuth = number | string | "leftwards" | "rightwards";
export type backdropFilter = "none" | string;
export type backfaceVisibility = "visible" | "hidden";
type backgroundSyntax = {
  attachment?: attachmentT;
  color?: colorT;
  image?: bgImageT;
  position?: string;
  repeat?: repeatStyleT;
};
export type background = string | finalBgLayerT | backgroundSyntax;
export type backgroundAttachment = attachmentT;
export type backgroundBlendMode = blendModeT;
export type backgroundClip = boxT;
export type backgroundColor = colorT;
export type backgroundImage = bgImageT;
export type backgroundOrigin = boxT;
export type backgroundPosition = string;
export type backgroundPositionX = string;
export type backgroundPositionY = string;
export type backgroundRepeat = repeatStyleT;
export type backgroundSize = bgSizeT;
export type blockSize = width;
type borderSyntax = {
  width?: brWidthT;
  style?: brStyleT;
  color?: colorT;
};
export type border = brWidthT | brStyleT | colorT | borderSyntax;
export type borderBlockEnd = borderWidth | borderStyle | color;
export type borderBlockEndColor = color;
export type borderBlockEndStyle = borderStyle;
export type borderBlockEndWidth = borderWidth;
export type borderBlockStart = borderWidth | borderStyle | color;
export type borderBlockStartColor = color;
export type borderBlockStartStyle = borderStyle;
export type borderBlockStartWidth = borderWidth;
export type borderBottomLeftRadius = lengthPercentageT;
export type borderBottomRightRadius = lengthPercentageT;
export type borderBottomStyle = brStyleT;
export type borderBottomWidth = brWidthT;
export type borderCollapse = "collapse" | "separate";
export type borderColor = colorT;
export type borderImage = borderImageSource | borderImageSlice | string | borderImageRepeat;
export type borderImageOutset = string;
export type borderImageRepeat = string;
export type borderImageSlice = numberPercentageT | "fill";
export type borderImageSource = "none" | string;
export type borderImageWidth = string;
export type borderInlineEnd = borderWidth | borderStyle | color;
export type borderInlineEndColor = color;
export type borderInlineEndStyle = borderStyle;
export type borderInlineEndWidth = borderWidth;
export type borderInlineStart = borderWidth | borderStyle | color;
export type borderInlineStartColor = color;
export type borderInlineStartStyle = borderStyle;
export type borderInlineStartWidth = borderWidth;
export type borderLeftColor = colorT;
export type borderLeftStyle = brStyleT;
export type borderLeftWidth = brWidthT;
export type borderRadius = lengthPercentageT | string;
export type borderRightColor = colorT;
export type borderRightStyle = brStyleT;
export type borderRightWidth = brWidthT;
export type borderSpacing = number;
export type borderStyle = brStyleT;
export type borderTopLeftRadius = lengthPercentageT;
export type borderTopRightRadius = lengthPercentageT;
export type borderTopStyle = brStyleT;
export type borderTopWidth = brWidthT;
export type borderWidth = brWidthT;
export type boxAlign = "start" | "center" | "end" | "baseline" | "stretch";
export type boxDecorationBreak = "slice" | "clone";
export type boxDirection = "normal" | "reverse" | "inherit";
export type boxFlex = number;
export type boxFlexGroup = number;
export type boxLines = "single" | "multiple";
export type boxOrdinalGroup = number;
export type boxOrient = "horizontal" | "vertical" | "inline-axis" | "block-axis" | "inherit";
export type boxPack = "start" | "center" | "end" | "justify";
type boxShadowSyntax = {
  x?: number;
  y?: number;
  blur?: number;
  spread?: number;
  color?: string;
  inset?: boolean;
};
export type boxShadow =
  | "none"
  | string
  | boxShadowSyntax
  | Array<string | boxShadowSyntax>;
export type boxSizing = "content-box" | "border-box";
export type boxSuppress = "show" | "discard" | "hide";
export type breakAfter = "auto" | "avoid" | "avoid-page" | "page" | "left" | "right" | "recto" | "verso" | "avoid-column" | "column" | "avoid-region" | "region";
export type breakBefore = "auto" | "avoid" | "avoid-page" | "page" | "left" | "right" | "recto" | "verso" | "avoid-column" | "column" | "avoid-region" | "region";
export type breakInside = "auto" | "avoid" | "avoid-page" | "avoid-column" | "avoid-region";
export type captionSide = "top" | "bottom" | "block-start" | "block-end" | "inline-start" | "inline-end";
export type clear = "none" | "left" | "right" | "both" | "inline-start" | "inline-end";
export type clip = string | "auto";
export type clipPath = string | "none";
export type color = colorT;
export type columnCount = number | "auto";
export type columnFill = "auto" | "balance";
export type columnGap = number | "normal";
export type columnRule = columnRuleWidth | columnRuleStyle | columnRuleColor;
export type columnRuleColor = colorT;
export type columnRuleStyle = brStyleT;
export type columnRuleWidth = brWidthT;
export type columnSpan = "none" | "all";
export type columnWidth = number | "auto";
export type columns = columnWidth | columnCount;
export type contain = "none" | "strict" | "content" | string;
export type content = string;
export type counterIncrement = string | "none";
export type counterReset = string | "none";
export type cursor = 'auto' | 'default' | 'none' | 'context-menu' | 'help' | 'pointer' | 'progress' | 'wait' | 'cell' | 'crosshair' | 'text' | 'vertical-text' | 'alias' | 'copy' | 'move' | 'no-drop' | 'not-allowed' | 'e-resize' | 'n-resize' | 'ne-resize' | 'nw-resize' | 's-resize' | 'se-resize' | 'sw-resize' | 'w-resize' | 'ew-resize' | 'ns-resize' | 'nesw-resize' | 'nwse-resize' | 'col-resize' | 'row-resize' | 'all-scroll' | 'zoom-in' | 'zoom-out' | 'grab' | 'grabbing';
export type direction = "ltr" | "rtl";
export type display = "none" | "inline" | "block" | "list-item" | "inline-list-item" | "inline-block" | "inline-table" | "table" | "table-cell" | "table-column" | "table-column-group" | "table-footer-group" | "table-header-group" | "table-row" | "table-row-group" | "flex" | "inline-flex" | "grid" | "inline-grid" | "run-in" | "ruby" | "ruby-base" | "ruby-text" | "ruby-base-container" | "ruby-text-container" | "contents" | "-ms-flexbox" | "-ms-inline-flexbox" | "-ms-grid" | "-ms-inline-grid" | "-webkit-flex" | "-webkit-inline-flex" | "-webkit-box" | "-webkit-inline-box" | "-moz-inline-stack" | "-moz-box" | "-moz-inline-box";
export type displayInside = "auto" | "block" | "table" | "flex" | "grid" | "ruby";
export type displayList = "none" | "list-item";
export type displayOutside = "block-level" | "inline-level" | "run-in" | "contents" | "none" | "table-row-group" | "table-header-group" | "table-footer-group" | "table-row" | "table-cell" | "table-column-group" | "table-column" | "table-caption" | "ruby-base" | "ruby-text" | "ruby-base-container" | "ruby-text-container";
export type emptyCells = "show" | "hide";
export type filter = "none" | string;
export type flex = "none" | string;
export type flexBasis = "content" | width;
export type flexDirection = "row" | "row-reverse" | "column" | "column-reverse";
export type flexFlow = flexDirection | flexWrap;
export type flexGrow = number;
export type flexShrink = number;
export type flexWrap = "nowrap" | "wrap" | "wrap-reverse";
export type float = "left" | "right" | "none" | "inline-start" | "inline-end";
export type font = string | "caption" | "icon" | "menu" | "message-box" | "small-caption" | "status-bar";
export type fontFamily = string;
export type fontFeatureSettings = "normal" | string;
export type fontKerning = "auto" | "normal" | "none";
export type fontLanguageOverride = "normal" | string;
export type fontSize = absoluteSizeT | relativeSizeT | lengthPercentageT;
export type fontSizeAdjust = "none" | number;
export type fontStretch = "normal" | "ultra-condensed" | "extra-condensed" | "condensed" | "semi-condensed" | "semi-expanded" | "expanded" | "extra-expanded" | "ultra-expanded";
export type fontStyle = "normal" | "italic" | "oblique";
export type fontSynthesis = "none" | string;
export type fontVariant = "normal" | "none" | string;
export type fontVariantAlternates = "normal" | string;
export type fontVariantCaps = "normal" | "small-caps" | "all-small-caps" | "petite-caps" | "all-petite-caps" | "unicase" | "titling-caps";
export type fontVariantEastAsian = "normal" | string;
export type fontVariantLigatures = "normal" | "none" | string;
export type fontVariantNumeric = "normal" | string;
export type fontVariantPosition = "normal" | "sub" | "super";
export type fontWeight = "normal" | "bold" | "bolder" | "lighter" | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
export type grid = gridTemplate | string;
export type gridArea = gridLineT | string;
export type gridAutoColumns = trackSizeT;
export type gridAutoFlow = string | "dense";
export type gridAutoRows = trackSizeT;
export type gridColumn = gridLineT | string;
export type gridColumnEnd = gridLineT;
export type gridColumnGap = lengthPercentageT;
export type gridColumnStart = gridLineT;
export type gridGap = gridRowGap | gridColumnGap;
export type gridRow = gridLineT | string;
export type gridRowEnd = gridLineT;
export type gridRowGap = lengthPercentageT;
export type gridRowStart = gridLineT;
export type gridTemplate = "none" | "subgrid" | string;
export type gridTemplateAreas = "none" | string;
export type gridTemplateColumns = "none" | "subgrid" | string;
export type gridTemplateRows = "none" | "subgrid" | string;
export type hyphens = "none" | "manual" | "auto";
export type imageOrientation = "from-image" | number | string;
export type imageRendering = "auto" | "crisp-edges" | "pixelated" | "optimizeSpeed" | "optimizeQuality" | nonStandartImageRenderingT;
export type imageResolution = string | "snap";
export type imeMode = "auto" | "normal" | "active" | "inactive" | "disabled";
export type initialLetter = "normal" | string;
export type initialLetterAlign = string;
export type inlineSize = width;
export type isolation = "auto" | "isolate";
export type justifyContent = "flex-start" | "flex-end" | "center" | "space-between" | "space-around";
export type letterSpacing = "normal" | lengthPercentageT;
export type lineBreak = "auto" | "loose" | "normal" | "strict";
export type lineHeight = "normal" | number | string;
export type listStyle = listStyleType | listStylePosition | listStyleImage;
export type listStyleImage = string | "none";
export type listStylePosition = "inside" | "outside";
export type listStyleType = string | "none";
type marginSyntax = {
  top?: number | string;
  left?: number | string;
  right?: number | string;
  bottom?: number | string;
};
export type margin = number | string | marginSyntax;
export type marginBlockEnd = marginLeft;
export type marginBlockStart = marginLeft;
export type marginBottom = number | string | "auto";
export type marginInlineEnd = marginLeft;
export type marginInlineStart = marginLeft;
export type marginLeft = number | string | "auto";
export type marginRight = number | string | "auto";
export type marginTop = number | string | "auto";
export type markerOffset = number | "auto";
export type mask = maskLayerT;
export type maskClip = string;
export type maskComposite = compositingOperatorT;
export type maskImage = maskReferenceT;
export type maskMode = maskingModeT;
export type maskOrigin = geometryBoxT;
export type maskPosition = string;
export type maskRepeat = repeatStyleT;
export type maskSize = bgSizeT;
export type maskType = "luminance" | "alpha";
export type maxBlockSize = maxWidth;
export type maxHeight = number | string | "none" | "max-content" | "min-content" | "fit-content" | "fill-available";
export type maxInlineSize = maxWidth;
export type maxWidth = number | string | "none" | "max-content" | "min-content" | "fit-content" | "fill-available" | nonStandartWidthT;
export type minBlockSize = minWidth;
export type minHeight = number | string | "auto" | "max-content" | "min-content" | "fit-content" | "fill-available";
export type minInlineSize = minWidth;
export type minWidth = number | string | "auto" | "max-content" | "min-content" | "fit-content" | "fill-available" | nonStandartWidthT;
export type mixBlendMode = blendModeT;
export type motion = motionPath | motionOffset | motionRotation;
export type motionOffset = lengthPercentageT;
export type motionPath = string | geometryBoxT | "none";
export type motionRotation = string | number;
export type objectFit = "fill" | "contain" | "cover" | "none" | "scale-down";
export type objectPosition = string;
export type offsetBlockEnd = string;
export type offsetBlockStart = string;
export type offsetInlineEnd = string;
export type offsetInlineStart = string;
export type opacity = number;
export type order = number;
export type orphans = number;
type outlineSyntax = {
  width?: brWidthT;
  style?: brStyleT;
  color?: colorT;
};
export type outline = string | outlineSyntax;
export type outlineColor = colorT | "invert";
export type outlineOffset = number;
export type outlineStyle = "auto" | brStyleT;
export type outlineWidth = brWidthT;
export type overflow = "visible" | "hidden" | "scroll" | "auto";
export type overflowClipBox = "padding-box" | "content-box";
export type overflowWrap = "normal" | "break-word";
export type overflowX = "visible" | "hidden" | "scroll" | "auto";
export type overflowY = "visible" | "hidden" | "scroll" | "auto";
type paddingSyntax = {
  top?: number | string;
  left?: number | string;
  right?: number | string;
  bottom?: number | string;
};
export type padding = number | string | paddingSyntax;
export type paddingBlockEnd = paddingLeft;
export type paddingBlockStart = paddingLeft;
export type paddingBottom = number | string;
export type paddingInlineEnd = paddingLeft;
export type paddingInlineStart = paddingLeft;
export type paddingLeft = number | string;
export type paddingRight = number | string;
export type paddingTop = number | string;
export type pageBreakAfter = "auto" | "always" | "avoid" | "left" | "right";
export type pageBreakBefore = "auto" | "always" | "avoid" | "left" | "right";
export type pageBreakInside = "auto" | "avoid";
export type perspective = "none" | number;
export type perspectiveOrigin = string;
export type pointerEvents = "auto" | "none" | "visiblePainted" | "visibleFill" | "visibleStroke" | "visible" | "painted" | "fill" | "stroke" | "all" | "inherit";
export type position = "static" | "relative" | "absolute" | "sticky" | "fixed";
export type quotes = string | "none";
export type resize = "none" | "both" | "horizontal" | "vertical";
export type rubyAlign = "start" | "center" | "space-between" | "space-around";
export type rubyMerge = "separate" | "collapse" | "auto";
export type rubyPosition = "over" | "under" | "inter-character";
export type scrollBehavior = "auto" | "smooth";
export type scrollSnapCoordinate = "none" | string;
export type scrollSnapDestination = string;
export type scrollSnapPointsX = "none" | string;
export type scrollSnapPointsY = "none" | string;
export type scrollSnapType = "none" | "mandatory" | "proximity";
export type scrollSnapTypeX = "none" | "mandatory" | "proximity";
export type scrollSnapTypeY = "none" | "mandatory" | "proximity";
export type shapeImageThreshold = number;
export type shapeMargin = lengthPercentageT;
export type shapeOutside = "none" | shapeBoxT | string;
export type tabSize = number;
export type tableLayout = "auto" | "fixed";
export type textAlign = "start" | "end" | "left" | "right" | "center" | "justify" | "match-parent";
export type textAlignLast = "auto" | "start" | "end" | "left" | "right" | "center" | "justify";
export type textCombineUpright = "none" | "all" | string;
export type textDecoration = textDecorationLine | textDecorationStyle | textDecorationColor;
export type textDecorationColor = colorT;
export type textDecorationLine = "none" | string;
export type textDecorationSkip = "none" | string;
export type textDecorationStyle = "solid" | "double" | "dotted" | "dashed" | "wavy";
export type textEmphasis = textEmphasisStyle | textEmphasisColor;
export type textEmphasisColor = colorT;
export type textEmphasisPosition = string;
export type textEmphasisStyle = "none" | string;
export type textIndent = string | "hanging" | "each-line";
export type textOrientation = "mixed" | "upright" | "sideways";
export type textOverflow = string;
export type textRendering = "auto" | "optimizeSpeed" | "optimizeLegibility" | "geometricPrecision";
type textShadowSyntax = {
  x?: number;
  y?: number;
  blur?: number;
  color?: string;
};
export type textShadow = "none" | string | textShadowSyntax;
export type textSizeAdjust = "none" | "auto" | string;
export type textTransform = "none" | "capitalize" | "uppercase" | "lowercase" | "full-width";
export type textUnderlinePosition = "auto" | string;
export type touchAction = "auto" | "none" | string | "manipulation";
export type transform = "none" | string;
export type transformBox = "border-box" | "fill-box" | "view-box";
export type transformOrigin = string | number;
export type transformStyle = "flat" | "preserve-3d";
type transitionSyntax = {
  property?: 'none' | singleTransitionPropertyT;
  duration?: number;
  timingFunction?: singleTransitionTimingFunctionT;
  delay?: number;
};
export type transition =
  | singleTransitionT
  | transitionSyntax
  | Array<singleTransitionT | transitionSyntax>;
export type transitionDelay = number;
export type transitionDuration = number;
export type transitionProperty = "none" | singleTransitionPropertyT;
export type transitionTimingFunction = singleTransitionTimingFunctionT;
export type unicodeBidi = "normal" | "embed" | "isolate" | "bidi-override" | "isolate-override" | "plaintext" | "-moz-isolate" | "-moz-isolate-override" | "-moz-plaintext" | "-webkit-isolate";
export type userSelect = "auto" | "text" | "none" | "contain" | "all";
export type verticalAlign = "baseline" | "sub" | "super" | "text-top" | "text-bottom" | "middle" | "top" | "bottom" | string | number;
export type visibility = "visible" | "hidden" | "collapse";
export type whiteSpace = "normal" | "pre" | "nowrap" | "pre-wrap" | "pre-line";
export type widows = number;
export type width = string | "available" | "min-content" | "max-content" | "fit-content" | "auto";
export type willChange = "auto" | animateableFeatureT;
export type wordBreak = "normal" | "break-all" | "keep-all" | nonStandartWordBreakT;
export type wordSpacing = "normal" | lengthPercentageT;
export type wordWrap = "normal" | "break-word";
export type writingMode = "horizontal-tb" | "vertical-rl" | "vertical-lr" | "sideways-rl" | "sideways-lr" | svgWritingModeT;
export type zIndex = "auto" | number;
export type mozBackgroundClip = "padding" | "border";
export type mozBorderRadiusBottomleft = borderBottomLeftRadius;
export type mozBorderRadiusBottomright = borderBottomRightRadius;
export type mozBorderRadiusTopleft = borderTopLeftRadius;
export type mozBorderRadiusTopright = borderBottomRightRadius;
export type mozOsxFontSmoothing = "auto" | "unset" | "grayscale";
export type mozUserSelect = "none" | "text" | "all" | "-moz-none";
export type msFilter = string;
export type msFlexAlign = "start" | "end" | "center" | "baseline" | "stretch";
export type msFlexItemAlign = "auto" | "start" | "end" | "center" | "baseline" | "stretch";
export type msFlexLinePack = "start" | "end" | "center" | "justify" | "distribute" | "stretch";
export type msFlexNegative = flexShrink;
export type msFlexPack = "start" | "end" | "center" | "justify" | "distribute";
export type msFlexOrder = number;
export type msFlexPositive = flexGrow;
export type msFlexPreferredSize = flexBasis;
export type msInterpolationMode = "nearest-neighbor" | "bicubic";
export type msGridColumnAlign = "start" | "end" | "center" | "stretch";
export type msGridRowAlign = "start" | "end" | "center" | "stretch";
export type msHighContrastAdjust = "auto" | "none";
export type msUserSelect = "none" | "element" | "text";
export type webkitAppearance = "none" | "button" | "button-bevel" | "caps-lock-indicator" | "caret" | "checkbox" | "default-button" | "listbox" | "listitem" | "media-fullscreen-button" | "media-mute-button" | "media-play-button" | "media-seek-back-button" | "media-seek-forward-button" | "media-slider" | "media-sliderthumb" | "menulist" | "menulist-button" | "menulist-text" | "menulist-textfield" | "push-button" | "radio" | "scrollbarbutton-down" | "scrollbarbutton-left" | "scrollbarbutton-right" | "scrollbarbutton-up" | "scrollbargripper-horizontal" | "scrollbargripper-vertical" | "scrollbarthumb-horizontal" | "scrollbarthumb-vertical" | "scrollbartrack-horizontal" | "scrollbartrack-vertical" | "searchfield" | "searchfield-cancel-button" | "searchfield-decoration" | "searchfield-results-button" | "searchfield-results-decoration" | "slider-horizontal" | "slider-vertical" | "sliderthumb-horizontal" | "sliderthumb-vertical" | "square-button" | "textarea" | "textfield";
export type webkitBackgroundClip = string;
export type webkitColumnBreakAfter = "always" | "auto" | "avoid";
export type webkitColumnBreakBefore = "always" | "auto" | "avoid";
export type webkitColumnBreakInside = "always" | "auto" | "avoid";
export type webkitFontSmoothing = "none" | "antialiased" | "subpixel-antialiased";
export type webkitLineClamp = number;
export type webkitMaskBoxImage = string;
export type webkitOverflowScrolling = "auto" | "touch";
export type webkitPrintColorAdjust = "economy" | "exact";
export type webkitTextSecurity = "none" | "circle" | "disc" | "square";
export type webkitUserDrag = "none" | "element" | "auto";
export type webkitUserSelect = "auto" | "none" | "text" | "all";
export type alignmentBaseline = "auto" | "baseline" | "before-edge" | "text-before-edge" | "middle" | "central" | "after-edge" | "text-after-edge" | "ideographic" | "alphabetic" | "hanging" | "mathematical";
export type baselineShift = "baseline" | "sub" | "super" | svgLengthT;
export type behavior = string;
export type clipRule = "nonzero" | "evenodd";
export type cue = cueBefore | cueAfter;
export type cueAfter = string | number | "none";
export type cueBefore = string | number | "none";
export type dominantBaseline = "auto" | "use-script" | "no-change" | "reset-size" | "ideographic" | "alphabetic" | "hanging" | "mathematical" | "central" | "middle" | "text-after-edge" | "text-before-edge";
export type fill = paintT;
export type fillOpacity = number;
export type fillRule = "nonzero" | "evenodd";
export type glyphOrientationHorizontal = number;
export type glyphOrientationVertical = number;
export type kerning = "auto" | svgLengthT;
export type marker = "none" | string;
export type markerEnd = "none" | string;
export type markerMid = "none" | string;
export type markerStart = "none" | string;
export type pause = pauseBefore | pauseAfter;
export type pauseAfter = number | "none" | "x-weak" | "weak" | "medium" | "strong" | "x-strong";
export type pauseBefore = number | "none" | "x-weak" | "weak" | "medium" | "strong" | "x-strong";
export type rest = restBefore | restAfter;
export type restAfter = number | "none" | "x-weak" | "weak" | "medium" | "strong" | "x-strong";
export type restBefore = number | "none" | "x-weak" | "weak" | "medium" | "strong" | "x-strong";
export type shapeRendering = "auto" | "optimizeSpeed" | "crispEdges" | "geometricPrecision";
export type src = string;
export type speak = "auto" | "none" | "normal";
export type speakAs = "normal" | "spell-out" | "digits" | string;
export type stroke = paintT;
export type strokeDasharray = "none" | string;
export type strokeDashoffset = svgLengthT;
export type strokeLinecap = "butt" | "round" | "square";
export type strokeLinejoin = "miter" | "round" | "bevel";
export type strokeMiterlimit = number;
export type strokeOpacity = number;
export type strokeWidth = svgLengthT;
export type textAnchor = "start" | "middle" | "end";
export type unicodeRange = string;
export type voiceBalance = number | "left" | "center" | "right" | "leftwards" | "rightwards";
export type voiceDuration = "auto" | number;
export type voiceFamily = string | "preserve";
export type voicePitch = number | "absolute" | string;
export type voiceRange = number | "absolute" | string;
export type voiceRate = string;
export type voiceStress = "normal" | "strong" | "moderate" | "none" | "reduced";
export type voiceVolume = "silent" | string;
export type zoom = "normal" | "reset" | number | string;
export type absoluteSizeT = "xx-small" | "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
export type animateableFeatureT = "scroll-position" | "contents" | string;
export type attachmentT = "scroll" | "fixed" | "local";
export type bgImageT = "none" | string;
export type bgSizeT = string | "cover" | "contain";
export type boxT = "border-box" | "padding-box" | "content-box";
export type brStyleT = "none" | "hidden" | "dotted" | "dashed" | "solid" | "double" | "groove" | "ridge" | "inset" | "outset";
export type brWidthT = number | "thin" | "medium" | "thick";
export type colorT = string | namedColorT | "currentcolor" | deprecatedSystemColorT;
export type compositeStyleT = "clear" | "copy" | "source-over" | "source-in" | "source-out" | "source-atop" | "destination-over" | "destination-in" | "destination-out" | "destination-atop" | "xor";
export type compositingOperatorT = "add" | "subtract" | "intersect" | "exclude";
export type deprecatedSystemColorT = "ActiveBorder" | "ActiveCaption" | "AppWorkspace" | "Background" | "ButtonFace" | "ButtonHighlight" | "ButtonShadow" | "ButtonText" | "CaptionText" | "GrayText" | "Highlight" | "HighlightText" | "InactiveBorder" | "InactiveCaption" | "InactiveCaptionText" | "InfoBackground" | "InfoText" | "Menu" | "MenuText" | "Scrollbar" | "ThreeDDarkShadow" | "ThreeDFace" | "ThreeDHighlight" | "ThreeDLightShadow" | "ThreeDShadow" | "Window" | "WindowFrame" | "WindowText";
export type finalBgLayerT = bgImageT |string | repeatStyleT | attachmentT | boxT | backgroundColor;
export type geometryBoxT = shapeBoxT | "fill-box" | "stroke-box" | "view-box";
export type gridLineT = "auto" | string;
export type lengthPercentageT = number | string;
export type maskLayerT = maskReferenceT | maskingModeT | string | repeatStyleT | geometryBoxT | compositingOperatorT;
export type maskReferenceT = "none" | string;
export type maskingModeT = "alpha" | "luminance" | "match-source";
export type namedColorT = "transparent" | "aliceblue" | "antiquewhite" | "aqua" | "aquamarine" | "azure" | "beige" | "bisque" | "black" | "blanchedalmond" | "blue" | "blueviolet" | "brown" | "burlywood" | "cadetblue" | "chartreuse" | "chocolate" | "coral" | "cornflowerblue" | "cornsilk" | "crimson" | "cyan" | "darkblue" | "darkcyan" | "darkgoldenrod" | "darkgray" | "darkgreen" | "darkgrey" | "darkkhaki" | "darkmagenta" | "darkolivegreen" | "darkorange" | "darkorchid" | "darkred" | "darksalmon" | "darkseagreen" | "darkslateblue" | "darkslategray" | "darkslategrey" | "darkturquoise" | "darkviolet" | "deeppink" | "deepskyblue" | "dimgray" | "dimgrey" | "dodgerblue" | "firebrick" | "floralwhite" | "forestgreen" | "fuchsia" | "gainsboro" | "ghostwhite" | "gold" | "goldenrod" | "gray" | "green" | "greenyellow" | "grey" | "honeydew" | "hotpink" | "indianred" | "indigo" | "ivory" | "khaki" | "lavender" | "lavenderblush" | "lawngreen" | "lemonchiffon" | "lightblue" | "lightcoral" | "lightcyan" | "lightgoldenrodyellow" | "lightgray" | "lightgreen" | "lightgrey" | "lightpink" | "lightsalmon" | "lightseagreen" | "lightskyblue" | "lightslategray" | "lightslategrey" | "lightsteelblue" | "lightyellow" | "lime" | "limegreen" | "linen" | "magenta" | "maroon" | "mediumaquamarine" | "mediumblue" | "mediumorchid" | "mediumpurple" | "mediumseagreen" | "mediumslateblue" | "mediumspringgreen" | "mediumturquoise" | "mediumvioletred" | "midnightblue" | "mintcream" | "mistyrose" | "moccasin" | "navajowhite" | "navy" | "oldlace" | "olive" | "olivedrab" | "orange" | "orangered" | "orchid" | "palegoldenrod" | "palegreen" | "paleturquoise" | "palevioletred" | "papayawhip" | "peachpuff" | "peru" | "pink" | "plum" | "powderblue" | "purple" | "rebeccapurple" | "red" | "rosybrown" | "royalblue" | "saddlebrown" | "salmon" | "sandybrown" | "seagreen" | "seashell" | "sienna" | "silver" | "skyblue" | "slateblue" | "slategray" | "slategrey" | "snow" | "springgreen" | "steelblue" | "tan" | "teal" | "thistle" | "tomato" | "turquoise" | "violet" | "wheat" | "white" | "whitesmoke" | "yellow" | "yellowgreen" | nonStandartColorT;
export type numberPercentageT = number | string;
export type relativeSizeT = "larger" | "smaller";
export type repeatStyleT = "repeat-x" | "repeat-y" | string;
export type shapeBoxT = boxT | "margin-box";
export type singleAnimationT = number | singleTimingFunctionT | singleAnimationIterationCountT | singleAnimationDirectionT | singleAnimationFillModeT | singleAnimationPlayStateT | singleAnimationNameT;
export type singleAnimationDirectionT = "normal" | "reverse" | "alternate" | "alternate-reverse";
export type singleAnimationFillModeT = "none" | "forwards" | "backwards" | "both";
export type singleAnimationIterationCountT = "infinite" | number;
export type singleAnimationNameT = "none" | string;
export type singleAnimationPlayStateT = "running" | "paused";
export type singleTimingFunctionT = singleTransitionTimingFunctionT;
export type singleTransitionT = singleTransitionTimingFunctionT | string | number;
export type singleTransitionTimingFunctionT = "ease" | "linear" | "ease-in" | "ease-out" | "ease-in-out" | "step-start" | "step-end" | string;
export type singleTransitionPropertyT = "all" | string;
export type trackBreadthT = lengthPercentageT | string | "min-content" | "max-content" | "auto";
export type trackSizeT = trackBreadthT | string;
export type nonStandartColorT = "-moz-ButtonDefault" | "-moz-ButtonHoverFace" | "-moz-ButtonHoverText" | "-moz-CellHighlight" | "-moz-CellHighlightText" | "-moz-Combobox" | "-moz-ComboboxText" | "-moz-Dialog" | "-moz-DialogText" | "-moz-dragtargetzone" | "-moz-EvenTreeRow" | "-moz-Field" | "-moz-FieldText" | "-moz-html-CellHighlight" | "-moz-html-CellHighlightText" | "-moz-mac-accentdarkestshadow" | "-moz-mac-accentdarkshadow" | "-moz-mac-accentface" | "-moz-mac-accentlightesthighlight" | "-moz-mac-accentlightshadow" | "-moz-mac-accentregularhighlight" | "-moz-mac-accentregularshadow" | "-moz-mac-chrome-active" | "-moz-mac-chrome-inactive" | "-moz-mac-focusring" | "-moz-mac-menuselect" | "-moz-mac-menushadow" | "-moz-mac-menutextselect" | "-moz-MenuHover" | "-moz-MenuHoverText" | "-moz-MenuBarText" | "-moz-MenuBarHoverText" | "-moz-nativehyperlinktext" | "-moz-OddTreeRow" | "-moz-win-communicationstext" | "-moz-win-mediatext" | "-webkit-activelink" | "-webkit-focus-ring-color" | "-webkit-link" | "-webkit-text";
export type nonStandartImageRenderingT = "optimize-contrast" | "-moz-crisp-edges" | "-o-crisp-edges" | "-webkit-optimize-contrast";
export type nonStandartWidthT = "min-intrinsic" | "intrinsic" | "-moz-min-content" | "-moz-max-content" | "-webkit-min-content" | "-webkit-max-content";
export type nonStandartWordBreakT = "break-word";
export type webkitMaskClipStyleT = "border" | "border-box" | "padding" | "padding-box" | "content" | "content-box" | "text";
export type blendModeT = "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "color-dodge" | "color-burn" | "hard-light" | "soft-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity";
export type borderRadiusT = lengthPercentageT;
export type maskImageT = maskReferenceT;
export type outlineRadiusT = borderRadiusT;
export type paintT = "none" | "currentColor" | colorT | string;
export type svgLengthT = string | number;
export type svgWritingModeT = "lr-tb" | "rl-tb" | "tb-rl" | "lr" | "rl" | "tb";
export type CSSPropertySet = {|
  msOverflowStyle?: msOverflowStyle;
  mozAppearance?: mozAppearance;
  mozBinding?: mozBinding;
  mozBorderBottomColors?: mozBorderBottomColors;
  mozBorderLeftColors?: mozBorderLeftColors;
  mozBorderRightColors?: mozBorderRightColors;
  mozBorderTopColors?: mozBorderTopColors;
  mozFloatEdge?: mozFloatEdge;
  mozForceBrokenImageIcon?: mozForceBrokenImageIcon;
  mozImageRegion?: mozImageRegion;
  mozOrient?: mozOrient;
  mozOutlineRadius?: mozOutlineRadius;
  mozOutlineRadiusBottomleft?: mozOutlineRadiusBottomleft;
  mozOutlineRadiusBottomright?: mozOutlineRadiusBottomright;
  mozOutlineRadiusTopleft?: mozOutlineRadiusTopleft;
  mozOutlineRadiusTopright?: mozOutlineRadiusTopright;
  mozStackSizing?: mozStackSizing;
  mozTextBlink?: mozTextBlink;
  mozUserFocus?: mozUserFocus;
  mozUserInput?: mozUserInput;
  mozUserModify?: mozUserModify;
  mozWindowShadow?: mozWindowShadow;
  webkitBorderBefore?: webkitBorderBefore;
  webkitBorderBeforeColor?: webkitBorderBeforeColor;
  webkitBorderBeforeStyle?: webkitBorderBeforeStyle;
  webkitBorderBeforeWidth?: webkitBorderBeforeWidth;
  webkitBoxReflect?: webkitBoxReflect;
  webkitMask?: webkitMask;
  webkitMaskAttachment?: webkitMaskAttachment;
  webkitMaskClip?: webkitMaskClip;
  webkitMaskComposite?: webkitMaskComposite;
  webkitMaskImage?: webkitMaskImage;
  webkitMaskOrigin?: webkitMaskOrigin;
  webkitMaskPosition?: webkitMaskPosition;
  webkitMaskPositionX?: webkitMaskPositionX;
  webkitMaskPositionY?: webkitMaskPositionY;
  webkitMaskRepeat?: webkitMaskRepeat;
  webkitMaskRepeatX?: webkitMaskRepeatX;
  webkitMaskRepeatY?: webkitMaskRepeatY;
  webkitTapHighlightColor?: webkitTapHighlightColor;
  webkitTextFillColor?: webkitTextFillColor;
  webkitTextStroke?: webkitTextStroke;
  webkitTextStrokeColor?: webkitTextStrokeColor;
  webkitTextStrokeWidth?: webkitTextStrokeWidth;
  webkitTouchCallout?: webkitTouchCallout;
  alignContent?: alignContent;
  alignItems?: alignItems;
  alignSelf?: alignSelf;
  all?: all;
  animation?: animation;
  animationDelay?: animationDelay;
  animationDirection?: animationDirection;
  animationDuration?: animationDuration;
  animationFillMode?: animationFillMode;
  animationIterationCount?: animationIterationCount;
  animationName?: animationName;
  animationPlayState?: animationPlayState;
  animationTimingFunction?: animationTimingFunction;
  appearance?: appearance;
  azimuth?: azimuth;
  backdropFilter?: backdropFilter;
  backfaceVisibility?: backfaceVisibility;
  background?: background;
  backgroundAttachment?: backgroundAttachment;
  backgroundBlendMode?: backgroundBlendMode;
  backgroundClip?: backgroundClip;
  backgroundColor?: backgroundColor;
  backgroundImage?: backgroundImage;
  backgroundOrigin?: backgroundOrigin;
  backgroundPosition?: backgroundPosition;
  backgroundPositionX?: backgroundPositionX;
  backgroundPositionY?: backgroundPositionY;
  backgroundRepeat?: backgroundRepeat;
  backgroundSize?: backgroundSize;
  blockSize?: blockSize;
  border?: border;
  borderBlockEnd?: borderBlockEnd;
  borderBlockEndColor?: borderBlockEndColor;
  borderBlockEndStyle?: borderBlockEndStyle;
  borderBlockEndWidth?: borderBlockEndWidth;
  borderBlockStart?: borderBlockStart;
  borderBlockStartColor?: borderBlockStartColor;
  borderBlockStartStyle?: borderBlockStartStyle;
  borderBlockStartWidth?: borderBlockStartWidth;
  borderBottom?: border;
  borderBottomColor?: colorT;
  borderBottomLeftRadius?: borderBottomLeftRadius;
  borderBottomRightRadius?: borderBottomRightRadius;
  borderBottomStyle?: borderBottomStyle;
  borderBottomWidth?: borderBottomWidth;
  borderCollapse?: borderCollapse;
  borderColor?: borderColor;
  borderImage?: borderImage;
  borderImageOutset?: borderImageOutset;
  borderImageRepeat?: borderImageRepeat;
  borderImageSlice?: borderImageSlice;
  borderImageSource?: borderImageSource;
  borderImageWidth?: borderImageWidth;
  borderInlineEnd?: borderInlineEnd;
  borderInlineEndColor?: borderInlineEndColor;
  borderInlineEndStyle?: borderInlineEndStyle;
  borderInlineEndWidth?: borderInlineEndWidth;
  borderInlineStart?: borderInlineStart;
  borderInlineStartColor?: borderInlineStartColor;
  borderInlineStartStyle?: borderInlineStartStyle;
  borderInlineStartWidth?: borderInlineStartWidth;
  borderLeft?: border;
  borderLeftColor?: borderLeftColor;
  borderLeftStyle?: borderLeftStyle;
  borderLeftWidth?: borderLeftWidth;
  borderRadius?: borderRadius;
  borderRight?: border;
  borderRightColor?: borderRightColor;
  borderRightStyle?: borderRightStyle;
  borderRightWidth?: borderRightWidth;
  borderSpacing?: borderSpacing;
  borderStyle?: borderStyle;
  borderTop?: border;
  borderTopColor?: colorT;
  borderTopLeftRadius?: borderTopLeftRadius;
  borderTopRightRadius?: borderTopRightRadius;
  borderTopStyle?: borderTopStyle;
  borderTopWidth?: borderTopWidth;
  borderWidth?: borderWidth;
  bottom?: number | string;
  boxAlign?: boxAlign;
  boxDecorationBreak?: boxDecorationBreak;
  boxDirection?: boxDirection;
  boxFlex?: boxFlex;
  boxFlexGroup?: boxFlexGroup;
  boxLines?: boxLines;
  boxOrdinalGroup?: boxOrdinalGroup;
  boxOrient?: boxOrient;
  boxPack?: boxPack;
  boxShadow?: boxShadow;
  boxSizing?: boxSizing;
  boxSuppress?: boxSuppress;
  breakAfter?: breakAfter;
  breakBefore?: breakBefore;
  breakInside?: breakInside;
  captionSide?: captionSide;
  clear?: clear;
  clip?: clip;
  clipPath?: clipPath;
  color?: color;
  columnCount?: columnCount;
  columnFill?: columnFill;
  columnGap?: columnGap;
  columnRule?: columnRule;
  columnRuleColor?: columnRuleColor;
  columnRuleStyle?: columnRuleStyle;
  columnRuleWidth?: columnRuleWidth;
  columnSpan?: columnSpan;
  columnWidth?: columnWidth;
  columns?: columns;
  contain?: contain;
  content?: content;
  counterIncrement?: counterIncrement;
  counterReset?: counterReset;
  cursor?: cursor;
  direction?: direction;
  display?: display;
  displayInside?: displayInside;
  displayList?: displayList;
  displayOutside?: displayOutside;
  emptyCells?: emptyCells;
  filter?: filter;
  flex?: flex;
  flexBasis?: flexBasis;
  flexDirection?: flexDirection;
  flexFlow?: flexFlow;
  flexGrow?: flexGrow;
  flexShrink?: flexShrink;
  flexWrap?: flexWrap;
  float?: float;
  font?: font;
  fontFamily?: fontFamily;
  fontFeatureSettings?: fontFeatureSettings;
  fontKerning?: fontKerning;
  fontLanguageOverride?: fontLanguageOverride;
  fontSize?: fontSize;
  fontSizeAdjust?: fontSizeAdjust;
  fontStretch?: fontStretch;
  fontStyle?: fontStyle;
  fontSynthesis?: fontSynthesis;
  fontVariant?: fontVariant;
  fontVariantAlternates?: fontVariantAlternates;
  fontVariantCaps?: fontVariantCaps;
  fontVariantEastAsian?: fontVariantEastAsian;
  fontVariantLigatures?: fontVariantLigatures;
  fontVariantNumeric?: fontVariantNumeric;
  fontVariantPosition?: fontVariantPosition;
  fontWeight?: fontWeight;
  grid?: grid;
  gridArea?: gridArea;
  gridAutoColumns?: gridAutoColumns;
  gridAutoFlow?: gridAutoFlow;
  gridAutoRows?: gridAutoRows;
  gridColumn?: gridColumn;
  gridColumnEnd?: gridColumnEnd;
  gridColumnGap?: gridColumnGap;
  gridColumnStart?: gridColumnStart;
  gridGap?: gridGap;
  gridRow?: gridRow;
  gridRowEnd?: gridRowEnd;
  gridRowGap?: gridRowGap;
  gridRowStart?: gridRowStart;
  gridTemplate?: gridTemplate;
  gridTemplateAreas?: gridTemplateAreas;
  gridTemplateColumns?: gridTemplateColumns;
  gridTemplateRows?: gridTemplateRows;
  height?: number | string;
  hyphens?: hyphens;
  imageOrientation?: imageOrientation;
  imageRendering?: imageRendering;
  imageResolution?: imageResolution;
  imeMode?: imeMode;
  initialLetter?: initialLetter;
  initialLetterAlign?: initialLetterAlign;
  inlineSize?: inlineSize;
  isolation?: isolation;
  justifyContent?: justifyContent;
  left?: number | string;
  letterSpacing?: letterSpacing;
  lineBreak?: lineBreak;
  lineHeight?: lineHeight;
  listStyle?: listStyle;
  listStyleImage?: listStyleImage;
  listStylePosition?: listStylePosition;
  listStyleType?: listStyleType;
  margin?: margin;
  marginBlockEnd?: marginBlockEnd;
  marginBlockStart?: marginBlockStart;
  marginBottom?: marginBottom;
  marginInlineEnd?: marginInlineEnd;
  marginInlineStart?: marginInlineStart;
  marginLeft?: marginLeft;
  marginRight?: marginRight;
  marginTop?: marginTop;
  markerOffset?: markerOffset;
  mask?: mask;
  maskClip?: maskClip;
  maskComposite?: maskComposite;
  maskImage?: maskImage;
  maskMode?: maskMode;
  maskOrigin?: maskOrigin;
  maskPosition?: maskPosition;
  maskRepeat?: maskRepeat;
  maskSize?: maskSize;
  maskType?: maskType;
  maxBlockSize?: maxBlockSize;
  maxHeight?: maxHeight;
  maxInlineSize?: maxInlineSize;
  maxWidth?: maxWidth;
  minBlockSize?: minBlockSize;
  minHeight?: minHeight;
  minInlineSize?: minInlineSize;
  minWidth?: minWidth;
  mixBlendMode?: mixBlendMode;
  motion?: motion;
  motionOffset?: motionOffset;
  motionPath?: motionPath;
  motionRotation?: motionRotation;
  objectFit?: objectFit;
  objectPosition?: objectPosition;
  offsetBlockEnd?: offsetBlockEnd;
  offsetBlockStart?: offsetBlockStart;
  offsetInlineEnd?: offsetInlineEnd;
  offsetInlineStart?: offsetInlineStart;
  opacity?: opacity;
  order?: order;
  orphans?: orphans;
  outline?: outline;
  outlineColor?: outlineColor;
  outlineOffset?: outlineOffset;
  outlineStyle?: outlineStyle;
  outlineWidth?: outlineWidth;
  overflow?: overflow;
  overflowClipBox?: overflowClipBox;
  overflowWrap?: overflowWrap;
  overflowX?: overflowX;
  overflowY?: overflowY;
  padding?: padding;
  paddingBlockEnd?: paddingBlockEnd;
  paddingBlockStart?: paddingBlockStart;
  paddingBottom?: paddingBottom;
  paddingInlineEnd?: paddingInlineEnd;
  paddingInlineStart?: paddingInlineStart;
  paddingLeft?: paddingLeft;
  paddingRight?: paddingRight;
  paddingTop?: paddingTop;
  paddingH?: number | string;
  paddingV?: number | string;
  marginH?: number | string;
  marginV?: number | string;
  pageBreakAfter?: pageBreakAfter;
  pageBreakBefore?: pageBreakBefore;
  pageBreakInside?: pageBreakInside;
  perspective?: perspective;
  perspectiveOrigin?: perspectiveOrigin;
  pointerEvents?: pointerEvents;
  position?: position;
  quotes?: quotes;
  resize?: resize;
  right?: number | string;
  rubyAlign?: rubyAlign;
  rubyMerge?: rubyMerge;
  rubyPosition?: rubyPosition;
  scrollBehavior?: scrollBehavior;
  scrollSnapCoordinate?: scrollSnapCoordinate;
  scrollSnapDestination?: scrollSnapDestination;
  scrollSnapPointsX?: scrollSnapPointsX;
  scrollSnapPointsY?: scrollSnapPointsY;
  scrollSnapType?: scrollSnapType;
  scrollSnapTypeX?: scrollSnapTypeX;
  scrollSnapTypeY?: scrollSnapTypeY;
  shapeImageThreshold?: shapeImageThreshold;
  shapeMargin?: shapeMargin;
  shapeOutside?: shapeOutside;
  tabSize?: tabSize;
  tableLayout?: tableLayout;
  textAlign?: textAlign;
  textAlignLast?: textAlignLast;
  textCombineUpright?: textCombineUpright;
  textDecoration?: textDecoration;
  textDecorationColor?: textDecorationColor;
  textDecorationLine?: textDecorationLine;
  textDecorationSkip?: textDecorationSkip;
  textDecorationStyle?: textDecorationStyle;
  textEmphasis?: textEmphasis;
  textEmphasisColor?: textEmphasisColor;
  textEmphasisPosition?: textEmphasisPosition;
  textEmphasisStyle?: textEmphasisStyle;
  textIndent?: textIndent;
  textOrientation?: textOrientation;
  textOverflow?: textOverflow;
  textRendering?: textRendering;
  textShadow?: textShadow;
  textSizeAdjust?: textSizeAdjust;
  textTransform?: textTransform;
  textUnderlinePosition?: textUnderlinePosition;
  top?: number | string;
  touchAction?: touchAction;
  transform?: transform;
  transformBox?: transformBox;
  transformOrigin?: transformOrigin;
  transformStyle?: transformStyle;
  transition?: transition;
  transitionDelay?: transitionDelay;
  transitionDuration?: transitionDuration;
  transitionProperty?: transitionProperty;
  transitionTimingFunction?: transitionTimingFunction;
  unicodeBidi?: unicodeBidi;
  userSelect?: userSelect;
  verticalAlign?: verticalAlign;
  visibility?: visibility;
  whiteSpace?: whiteSpace;
  widows?: widows;
  width?: number | string;
  willChange?: willChange;
  wordBreak?: wordBreak;
  wordSpacing?: wordSpacing;
  wordWrap?: wordWrap;
  writingMode?: writingMode;
  zIndex?: zIndex;
  mozBackgroundClip?: mozBackgroundClip;
  mozBorderRadiusBottomleft?: mozBorderRadiusBottomleft;
  mozBorderRadiusBottomright?: mozBorderRadiusBottomright;
  mozBorderRadiusTopleft?: mozBorderRadiusTopleft;
  mozBorderRadiusTopright?: mozBorderRadiusTopright;
  mozOsxFontSmoothing?: mozOsxFontSmoothing;
  mozUserSelect?: mozUserSelect;
  msFilter?: msFilter;
  msFlexAlign?: msFlexAlign;
  msFlexItemAlign?: msFlexItemAlign;
  msFlexLinePack?: msFlexLinePack;
  msFlexNegative?: msFlexNegative;
  msFlexPack?: msFlexPack;
  msFlexOrder?: msFlexOrder;
  msFlexPositive?: msFlexPositive;
  msFlexPreferredSize?: msFlexPreferredSize;
  msInterpolationMode?: msInterpolationMode;
  msGridColumnAlign?: msGridColumnAlign;
  msGridRowAlign?: msGridRowAlign;
  msHighContrastAdjust?: msHighContrastAdjust;
  msUserSelect?: msUserSelect;
  webkitAppearance?: webkitAppearance;
  webkitBackgroundClip?: webkitBackgroundClip;
  webkitColumnBreakAfter?: webkitColumnBreakAfter;
  webkitColumnBreakBefore?: webkitColumnBreakBefore;
  webkitColumnBreakInside?: webkitColumnBreakInside;
  webkitFontSmoothing?: webkitFontSmoothing;
  webkitLineClamp?: webkitLineClamp;
  webkitMaskBoxImage?: webkitMaskBoxImage;
  webkitOverflowScrolling?: webkitOverflowScrolling;
  webkitPrintColorAdjust?: webkitPrintColorAdjust;
  webkitTextSecurity?: webkitTextSecurity;
  webkitUserDrag?: webkitUserDrag;
  webkitUserSelect?: webkitUserSelect;
  alignmentBaseline?: alignmentBaseline;
  baselineShift?: baselineShift;
  behavior?: behavior;
  clipRule?: clipRule;
  cue?: cue;
  cueAfter?: cueAfter;
  cueBefore?: cueBefore;
  dominantBaseline?: dominantBaseline;
  fill?: fill;
  fillOpacity?: fillOpacity;
  fillRule?: fillRule;
  glyphOrientationHorizontal?: glyphOrientationHorizontal;
  glyphOrientationVertical?: glyphOrientationVertical;
  kerning?: kerning;
  marker?: marker;
  markerEnd?: markerEnd;
  markerMid?: markerMid;
  markerStart?: markerStart;
  pause?: pause;
  pauseAfter?: pauseAfter;
  pauseBefore?: pauseBefore;
  rest?: rest;
  restAfter?: restAfter;
  restBefore?: restBefore;
  shapeRendering?: shapeRendering;
  src?: src;
  speak?: speak;
  speakAs?: speakAs;
  stroke?: stroke;
  strokeDasharray?: strokeDasharray;
  strokeDashoffset?: strokeDashoffset;
  strokeLinecap?: strokeLinecap;
  strokeLinejoin?: strokeLinejoin;
  strokeMiterlimit?: strokeMiterlimit;
  strokeOpacity?: strokeOpacity;
  strokeWidth?: strokeWidth;
  textAnchor?: textAnchor;
  unicodeRange?: unicodeRange;
  voiceBalance?: voiceBalance;
  voiceDuration?: voiceDuration;
  voiceFamily?: voiceFamily;
  voicePitch?: voicePitch;
  voiceRange?: voiceRange;
  voiceRate?: voiceRate;
  voiceStress?: voiceStress;
  voiceVolume?: voiceVolume;
  zoom?: zoom;

  focus?: CSSPropertySet;
  hover?: CSSPropertySet;
  active?: CSSPropertySet;
  checked?: CSSPropertySet;
  default?: CSSPropertySet;
  disabled?: CSSPropertySet;
  empty?: CSSPropertySet;
  enabled?: CSSPropertySet;
  firstChild?: CSSPropertySet;
  firstOfType?: CSSPropertySet;
  lastOfType?: CSSPropertySet;
  fullscreen?: CSSPropertySet;
  indeterminate?: CSSPropertySet;
  invalid?: CSSPropertySet;
  lastChild?: CSSPropertySet;
  link?: CSSPropertySet;
  onlyChild?: CSSPropertySet;
  optional?: CSSPropertySet;
  required?: CSSPropertySet;
  root?: CSSPropertySet;
  scope?: CSSPropertySet;
  target?: CSSPropertySet;
  valid?: CSSPropertySet;
  visited?: CSSPropertySet;
|};
